# Generated by Django 4.2.27 on 2026-01-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_maquina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Fórmula',
                'verbose_name_plural': 'Fórmulas',
            },
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('metros_por_cono', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_minima', models.DecimalField(decimal_places=3, default=10, max_digits=12)),
                ('cantidad_maxima', models.DecimalField(decimal_places=3, default=1000, max_digits=12)),
                ('ubicacion', models.CharField(blank=True, help_text='Estante, armario, etc.', max_length=100)),
                ('codigo_ubicacion', models.CharField(blank=True, max_length=50)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_ultima_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Si está bloqueado, no se puede modificar')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tela', 'Tela'), ('hilo', 'Hilo'), ('avios', 'Avíos'), ('otro', 'Otro')], max_length=20)),
                ('unidad', models.CharField(default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('diario', '📊 Diario'), ('semanal', '📈 Semanal'), ('mensual', '📉 Mensual'), ('anual', '📋 Anual'), ('especial', '🎯 Especial')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_materiales', models.PositiveIntegerField(default=0)),
                ('materiales_bajos', models.PositiveIntegerField(default=0)),
                ('valor_total_inventario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('movimientos_totales', models.PositiveIntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes_inventario/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField(blank=True)),
                ('hallazgos', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Inventario',
                'verbose_name_plural': 'Reportes de Inventario',
                'ordering': ['-periodo_fin'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=200)),
                ('contacto_proveedor', models.CharField(blank=True, max_length=100)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_esperada', models.DateField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobado', '✅ Aprobado'), ('ordenado', '📦 Ordenado'), ('recibido', '📥 Recibido'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_orden_compra', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_aprobados', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', '➕ Entrada'), ('salida', '➖ Salida'), ('ajuste', '📝 Ajuste'), ('inicial', '📦 Stock Inicial'), ('transferencia', '🔄 Transferencia'), ('devolucion', '↪️ Devolución')], max_length=20)),
                ('origen', models.CharField(choices=[('compra', '🛒 Compra'), ('produccion', '🏭 Producción'), ('ajuste_inventario', '📊 Ajuste de Inventario'), ('venta', '💰 Venta'), ('danado', '⚠️ Dañado'), ('caducado', '📅 Caducado'), ('otros', '❓ Otros')], default='compra', max_length=20)),
                ('cantidad_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_movimiento', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Nº Factura, Orden, etc.', max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='materiales.inventario')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.ordenproduccion')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='materiales.material'),
        ),
        migrations.CreateModel(
            name='HistoricoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_costo', to='materiales.material')),
            ],
            options={
                'verbose_name': 'Histórico de Costo',
                'verbose_name_plural': 'Históricos de Costos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FormulaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='materiales.formula')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Detalle de Fórmula',
                'verbose_name_plural': 'Detalles de Fórmula',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('costo_unitario_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='materiales.pedidocompra')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Compra',
                'verbose_name_plural': 'Detalles de Pedidos de Compra',
            },
        ),
        migrations.CreateModel(
            name='ConsumoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_hilo_por_metro_tela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.configuracionmaquina')),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.tela')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionHilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hilos', to='materiales.configuracionmaquina')),
                ('hilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.hilo')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_minimo', '📉 Stock por debajo del mínimo'), ('stock_maximo', '📈 Stock por encima del máximo'), ('sin_movimientos', '🔄 Sin movimientos recientes'), ('costo_alto', '💰 Costo elevado')], max_length=20)),
                ('nivel', models.CharField(choices=[('bajo', '🔴 Crítico'), ('medio', '🟡 Bajo'), ('alto', '🟢 Normal')], default='bajo', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cantidad_umbral', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('accion_tomada', models.TextField(blank=True)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.inventario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='materiales.material')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('material', 'ubicacion')},
        ),
        migrations.CreateModel(
            name='ConsumoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('desperdicio_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de desperdicio', max_digits=5)),
                ('costo_material_por_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Consumo por Producto',
                'verbose_name_plural': 'Consumos por Producto',
                'unique_together': {('producto', 'material')},
            },
        ),
    ]
