# Generated by Django 5.2.10 on 2026-02-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionhilo',
            options={'verbose_name': 'Configuración de Hilo', 'verbose_name_plural': 'Configuraciones de Hilo'},
        ),
        migrations.AlterModelOptions(
            name='configuracionmaquina',
            options={'verbose_name': 'Configuración de Máquina', 'verbose_name_plural': 'Configuraciones de Máquina'},
        ),
        migrations.AlterModelOptions(
            name='consumotela',
            options={'verbose_name': 'Consumo de Tela', 'verbose_name_plural': 'Consumos de Tela'},
        ),
        migrations.AlterModelOptions(
            name='hilo',
            options={'verbose_name': 'Hilo', 'verbose_name_plural': 'Hilos'},
        ),
        migrations.AlterModelOptions(
            name='tela',
            options={'verbose_name': 'Tela', 'verbose_name_plural': 'Telas'},
        ),
        migrations.AddField(
            model_name='hilo',
            name='codigo_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hilo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='codigo_color',
            field=models.CharField(blank=True, help_text='Código interno del color', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tela',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Ancho en metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='tela',
            name='codigo_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tela',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tela',
            name='tipo_tela',
            field=models.CharField(blank=True, help_text='Ej: Algodón, Poliéster, etc.', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hilo',
            unique_together={('nombre', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('nombre', 'tipo', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='tela',
            unique_together={('nombre', 'color')},
        ),
    ]
