# Generated by Django 5.2.10 on 2026-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', null=True, upload_to='profile_images/', verbose_name='Foto de perfil'),
        ),
    ]
