# Generated by Django 4.2.27 on 2026-01-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produccion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('estandar', '⚙️ Estándar'), ('personalizado', '🎨 Personalizado'), ('rapido', '⚡ Rápido'), ('premium', '👑 Premium')], default='estandar', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_preparacion', models.PositiveIntegerField(default=30, help_text='Tiempo en minutos')),
                ('tiempo_confeccion', models.PositiveIntegerField(default=60, help_text='Tiempo en minutos por unidad')),
                ('tiempo_acabado', models.PositiveIntegerField(default=15, help_text='Tiempo en minutos')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_maquinaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instrucciones', models.TextField(blank=True)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='metodos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Producción',
                'verbose_name_plural': 'Métodos de Producción',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=produccion.models.generar_codigo_orden, max_length=50, unique=True)),
                ('fecha_programada', models.DateField(default=produccion.models.fecha_programada_default)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('programada', '📅 Programada'), ('en_proceso', '⚙️ En Proceso'), ('pausada', '⏸️ Pausada'), ('completada', '✅ Completada'), ('cancelada', '❌ Cancelada')], default='programada', max_length=20)),
                ('progreso', models.PositiveIntegerField(default=0, help_text='Progreso en porcentaje (0-100)')),
                ('cantidad_a_producir', models.PositiveIntegerField()),
                ('cantidad_producida', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('incidencias', models.TextField(blank=True)),
                ('equipo', models.ManyToManyField(blank=True, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.metodoproduccion')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('semanal', '📅 Semanal'), ('mensual', '📆 Mensual'), ('diaria', '📋 Diaria')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('completada', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ReporteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('diario', '📊 Diario'), ('semanal', '📈 Semanal'), ('mensual', '📉 Mensual'), ('anual', '📋 Anual'), ('especial', '🎯 Especial')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('pedidos_completados', models.PositiveIntegerField(default=0)),
                ('pedidos_pendientes', models.PositiveIntegerField(default=0)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField(blank=True)),
                ('hallazgos', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Producción',
                'verbose_name_plural': 'Reportes de Producción',
                'ordering': ['-periodo_fin'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField()),
                ('turno', models.CharField(choices=[('manana', '🌅 Mañana'), ('tarde', '🌞 Tarde'), ('noche', '🌙 Noche')], default='manana', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.planificacion')),
            ],
            options={
                'ordering': ['fecha_asignada', 'turno', 'prioridad'],
                'unique_together': {('orden', 'fecha_asignada', 'turno')},
            },
        ),
        migrations.AddField(
            model_name='planificacion',
            name='ordenes',
            field=models.ManyToManyField(blank=True, through='produccion.PlanificacionOrden', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='planificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=produccion.models.generar_codigo_pedido, max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(default=produccion.models.fecha_entrega_default)),
                ('estado', models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('en_proceso', '🟠 En Proceso'), ('completado', '🟢 Completado'), ('cancelado', '🔴 Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(choices=[(1, '🔵 Baja'), (2, '🟡 Media'), (3, '🔴 Alta'), (4, '⚠️ Urgente')], default=1)),
                ('especificaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_diseno', models.FileField(blank=True, null=True, upload_to='disenos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='produccion.pedido'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MetodoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tiempo_estimado', models.PositiveIntegerField(default=0, help_text='Tiempo en minutos')),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.metodoproduccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
