# Generated by Django 4.2.27 on 2026-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
