# Generated by Django 5.2.10 on 2026-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_ordenproduccion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoproduccion',
            name='tipo',
            field=models.CharField(choices=[('estandar', ' Estándar'), ('personalizado', ' Personalizado'), ('rapido', ' Rápido'), ('premium', ' Premium')], default='estandar', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('programada', ' Programada'), ('en_proceso', ' En Proceso'), ('pausada', ' Pausada'), ('completada', ' Completada'), ('cancelada', ' Cancelada')], default='programada', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', ' Pendiente'), ('en_proceso', ' En Proceso'), ('completado', ' Completado'), ('cancelado', ' Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.IntegerField(choices=[(1, ' Baja'), (2, ' Media'), (3, ' Alta'), (4, ' Urgente')], default=1),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='tipo',
            field=models.CharField(choices=[('semanal', ' Semanal'), ('mensual', ' Mensual'), ('diaria', ' Diaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planificacionorden',
            name='turno',
            field=models.CharField(choices=[('manana', ' Mañana'), ('tarde', ' Tarde'), ('noche', ' Noche')], default='manana', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteproduccion',
            name='tipo',
            field=models.CharField(choices=[('diario', ' Diario'), ('semanal', ' Semanal'), ('mensual', ' Mensual'), ('anual', ' Anual'), ('especial', ' Especial')], max_length=20),
        ),
    ]
