# Generated by Django 5.2.10 on 2026-01-31 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_metodoproduccion_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
                ('icono', models.CharField(default='fa-circle', max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Trazabilidad',
                'verbose_name_plural': 'Estados de Trazabilidad',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_aprobada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_rechazada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='codigo_lote',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_almacenamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_control_calidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_fin_produccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_inicio_produccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='requiere_control_calidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='resultado_control_calidad',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado'), ('reparacion', '🔧 Requiere Reparación'), ('parcial', '⚠️ Parcial')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='ubicacion_actual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='estado_trazabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='produccion.estadotrazabilidad'),
        ),
    ]
