# Generated by Django 4.2.27 on 2026-01-26 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado'), ('reparacion', '🔧 Requiere reparación'), ('revision', '🔍 En revisión')], default='revision', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('puntuacion_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_defectos', models.PositiveIntegerField(default=0)),
                ('costo_reparacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Control de Calidad',
                'verbose_name_plural': 'Controles de Calidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tiempo_estimado', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('tiempo_real', models.DurationField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa de Proceso',
                'verbose_name_plural': 'Etapas de Proceso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FlujoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('tiempo_total_estimado', models.DurationField(blank=True, null=True)),
                ('veces_utilizado', models.PositiveIntegerField(default=0)),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flujo de Trabajo',
                'verbose_name_plural': 'Flujos de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='MaterialProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(default='unidad', max_length=20)),
                ('desperdicio_estimado', models.DecimalField(decimal_places=2, default=0, help_text='% de desperdicio', max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Material por Proceso',
                'verbose_name_plural': 'Materiales por Proceso',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('corte', '✂️ Corte'), ('confeccion', '🧵 Confección'), ('planchado', '🧺 Planchado'), ('revision', '🔍 Revisión'), ('empaque', '📦 Empaque'), ('almacen', '📦 Almacén')], default='confeccion', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tiempo_estimado_min', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Tiempo mínimo estimado (HH:MM:SS)')),
                ('tiempo_estimado_max', models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Tiempo máximo estimado (HH:MM:SS)')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_proceso', '🔄 En Proceso'), ('completado', '✅ Completado'), ('detenido', '⛔ Detenido'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('veces_ejecutado', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio', models.DurationField(blank=True, null=True)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=0, help_text='% de eficiencia', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_creados', to=settings.AUTH_USER_MODEL)),
                ('materiales_necesarios', models.ManyToManyField(blank=True, through='procesos.MaterialProceso', to='materiales.material')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Temporizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_objetivo', models.DurationField(help_text='Tiempo objetivo para completar')),
                ('tiempo_transcurrido', models.DurationField(default=datetime.timedelta(0))),
                ('estado', models.CharField(choices=[('inactivo', '⏸️ Inactivo'), ('activo', '▶️ Activo'), ('pausado', '⏸️ Pausado'), ('completado', '✅ Completado')], default='inactivo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporizadores_creados', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.etapaproceso')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporizadores', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Temporizador',
                'verbose_name_plural': 'Temporizadores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('requiere_completar_anterior', models.BooleanField(default=True)),
                ('puede_paralelizar', models.BooleanField(default=False)),
                ('es_opcional', models.BooleanField(default=False)),
                ('tiempo_maximo_espera', models.DurationField(blank=True, help_text='Tiempo máximo de espera antes del siguiente proceso', null=True)),
                ('flujo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.flujotrabajo')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Proceso en Flujo',
                'verbose_name_plural': 'Procesos en Flujo',
                'ordering': ['orden'],
                'unique_together': {('flujo_trabajo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('calculo_materiales', 'Cálculo de materiales'), ('calculo_hilo', 'Cálculo de hilo'), ('proceso_iniciado', 'Proceso iniciado'), ('proceso_finalizado', 'Proceso finalizado'), ('control_calidad', 'Control de calidad'), ('no_conformidad', 'No conformidad detectada'), ('temporizador', 'Temporizador utilizado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('tiempo_empleado', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('reportada', '📋 Reportada'), ('analisis', '🔍 En análisis'), ('correccion', '🔧 En corrección'), ('verificada', '✅ Verificada'), ('cerrada', '📦 Cerrada')], default='reportada', max_length=20)),
                ('prioridad', models.IntegerField(choices=[(1, '🟢 Baja'), (2, '🟡 Media'), (3, '🔴 Alta'), (4, '⚫ Crítica')], default=2)),
                ('causa_raiz', models.TextField(blank=True)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('accion_preventiva', models.TextField(blank=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cantidad_afectada', models.PositiveIntegerField(default=1)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impacto_produccion', models.CharField(blank=True, max_length=100)),
                ('control_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.controlcalidad')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.proceso')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsable_correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_responsable', to=settings.AUTH_USER_MODEL)),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'No Conformidad',
                'verbose_name_plural': 'No Conformidades',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddField(
            model_name='materialproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.proceso'),
        ),
        migrations.AddField(
            model_name='flujotrabajo',
            name='procesos',
            field=models.ManyToManyField(through='procesos.ProcesoFlujo', to='procesos.proceso'),
        ),
        migrations.AddField(
            model_name='etapaproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='procesos.proceso'),
        ),
        migrations.CreateModel(
            name='ControlCalidadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_defecto', models.CharField(choices=[('costura', 'Problema de costura'), ('tela', 'Defecto en tela'), ('color', 'Problema de color'), ('talla', 'Error de talla'), ('terminacion', 'Terminación deficiente'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('severidad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], default=1)),
                ('ubicacion_defecto', models.CharField(blank=True, help_text='Ej: manga izquierda, espalda, etc.', max_length=100)),
                ('accion_tomada', models.TextField(blank=True)),
                ('requiere_reparacion', models.BooleanField(default=False)),
                ('tiempo_reparacion', models.DurationField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='control_calidad/')),
                ('notas', models.TextField(blank=True)),
                ('control_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='procesos.controlcalidad')),
            ],
            options={
                'verbose_name': 'Detalle de Control de Calidad',
                'verbose_name_plural': 'Detalles de Control de Calidad',
            },
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.etapaproceso'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesos.proceso'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materialproceso',
            unique_together={('proceso', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='etapaproceso',
            unique_together={('proceso', 'orden')},
        ),
    ]
