# Generated by Django 5.2.10 on 2026-01-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
        ('produccion', '0004_estadotrazabilidad_ordenproduccion_cantidad_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad', to='produccion.pedido'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades', to='produccion.ordenproduccion'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='accion',
            field=models.CharField(choices=[('calculo_materiales', 'Cálculo de materiales'), ('calculo_hilo', 'Cálculo de hilo'), ('proceso_iniciado', 'Proceso iniciado'), ('proceso_finalizado', 'Proceso finalizado'), ('control_calidad', 'Control de calidad'), ('no_conformidad', 'No conformidad detectada'), ('temporizador', 'Temporizador utilizado'), ('trazabilidad_lote', 'Trazabilidad de lote')], max_length=50),
        ),
    ]
