# Generated by Django 4.2.28 on 2026-02-05 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesos', '0002_controlcalidad_orden_produccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='orden_produccion',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='pedido',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='lote_orden',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote/Orden (opcional)'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='proceso',
            field=models.CharField(choices=[('', '---------'), ('Primera Revisión de corte', 'Paso por "Primera Revisión de corte"'), ('Overlock', 'Paso por "Overlock"'), ('Recta', 'Paso por "Recta"'), ('Collareta', 'Paso por "Collareta"'), ('Mesista', 'Paso por "Mesista"')], max_length=100, verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(choices=[('aprobado', '✅ Aprobado'), ('reparacion', '🔧 Reparación'), ('rechazado', '❌ Rechazado'), ('revision', '🔍 Revisión')], max_length=20),
        ),
    ]
