# Generated by Django 4.2.28 on 2026-02-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_remove_controlcalidad_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(choices=[('aprobado', ' Aprobado'), ('reparacion', ' Reparación'), ('rechazado', ' Rechazado'), ('revision', ' Revisión')], max_length=20),
        ),
    ]
