# Generated by Django 4.2.28 on 2026-02-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_alter_controlcalidad_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcalidad',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='revisado_por',
        ),
    ]
